### ISSUE TITLE
Plain Text missing from Syntax Specific settings

### ISSUE THREAD

**Issue by ghost** [deathaxe/sublime-commands#1]
Hey @deathaxe, thanks for your work with this package.
I found an issue (originally posted on GH's SublimeTextIssues): https://github.com/SublimeTextIssues/Core/issues/2380

### Summary

Plain Text syntax has vanished from the Syntax Specific settings.

### Expected behavior

Like with other syntaxes, the Command Palette should show **Plain Text (this view)** when invoking syntax specific settings for plain text.

### Actual behavior

No Plain Text syntax shows up on the Command Palette.

### Steps to reproduce

1. Open a Plain Text file.
2. Call **Preferences: Settings - Syntax Specific** on the Command Palette

### Environment

* Operating system and version:
  * Mac OS 10.11.6
* Monitor:
  * Resolution: 1440x900 
  * `dpi_scale` used in ST: 0
* Sublime Text:
  * Dev Channel Build 3175 / Stable Channel 3.1.1 Build 3176
  * 64 bit

**Comment by jrappen** [comment]
There're also `*.hidden-tmLanguage` files, which 75d1ee6 did not address.
