### ISSUE TITLE
Workaround for installing and keeping up to date through Package Control

### ISSUE THREAD

**Issue by ghost** [deathaxe/sublime-commands#2]
Hey @deathaxe.

What do you think about this method to be able to install and keep `sublime-commands` up to date, through Package Control?

1. Include an empty `.no-sublime-package` [file](https://packagecontrol.io/docs/customizing_packages) in the root of the package, so it's treated as an unpacked package, installing to `Packages/{Package Name}/` instead of `Installed Packages/{Package Name}/`.

2. Package can be submitted to Package Control or, if you feel it's best, added manually with instructions on how to do so, in the `README.md`. Something along these lines:

> If you want to use it to override ST's commands you'll need to clone this repo into Sublime Text's Packages path as Default or add it manually in Package Control's settings:

```
"repositories":
[
    "https://github.com/deathaxe/sublime-commands"
],
"package_name_map":
{
    "sublime-commands": "Default"
}
```

**Comment by deathaxe** [comment]
I won't think the package is accepted at Package Control as it overwrites core stuff, which might cause serious issues if once I may not keep up to date quickly enough with new ST builds.

What's the intention to handle it as `.no-sublime-package`? 

In place customization wouldn't break auto-updates. Therefore your own Default additions/overloads could no longer live in `Packages/Default` path. The content can easily be browsed via `View Package Resource` command or PackageResourceViewer. I can see disadvantages only.

A readme or even a little install script to add the setting (by running package control's add command) may by worth considering.

**Comment by ghost** [comment]
> What's the intention to handle it as `.no-sublime-package`?

Just so I can use the Package Control settings above and expect it to install to the right `Packages` dir (it causes issues if installed to the default `Installed Packages` dir, as you know).

> Therefore your own Default additions/overloads could no longer live in Packages/Default path

You're right. I was thinking of just using `sublime-commands` *as is*, without adding custom commands.

In short, I was just thinking of a way to install and forget without having to watch the repo and update through git.

Thanks for your view on this, I guess the current way may be best for the average user.
Closing, cheers @deathaxe!

**Comment by deathaxe** [comment]
> ... causes issues if installed to the default Installed Packages dir ...

Never tried, before. You're right - doesn't work.

But if I recall correct Package Control checks git repos as well. At least if using the `Upgrade Overwrite All` command. Not sure about autoupdate

**Comment by ghost** [comment]
> Not sure about autoupdate

I guess so too. From the [Docs](https://packagecontrol.io/docs/usage):

> **Add Repository**
Add a repository that is not included in the default channel. This allows users to install and automatically update packages from GitHub and BitBucket. To add a package hosted on GitHub, enter the URL in the form https://github.com/username/repo. Don’t include .git at the end!

**Comment by ghost** [comment]
Thanks for the update. Installed with Package Control and it's working great. BTW, just as an example, [Terminus](https://packagecontrol.io/packages/Terminus) is registered in Package Control but it also installs as a `.no-sublime-package` package. It's normal for some packages which use dependencies to install to the `Packages` dir.

On another note, thanks for the`View Package File` tip, I hadn't notice it until you mentioned it. Although I like and use PackageResourceViewer, I only use the open resource function, never the extract so, your package should be sufficient, meaning I can disable another plugin.

Cheers.

**Comment by michaelblyons** [comment]
The PC install from the ReadMe works fine, but I'm not sure that PC is keeping this package up to date.
