### ISSUE TITLE
Package Control update behaviour

### ISSUE THREAD

**Issue by michaelblyons** [deathaxe/sublime-commands#5]
I have my settings up as detailed at https://github.com/deathaxe/sublime-commands#package-control, but PC doesn't appear to notice new changes to this repo.

Interestingly, the "List Packages" and "Remove Package" commands do not list _either_ a "Default" package or a "sublime-commands" package. In `Package Control.sublime-settings`, I have an entry for "Default," and OverrideAudit confirms the diff between stock shipped packages and this repo from two commits ago.

I can easily imagine I have something set up wrong, but I don't know what.

**Comment by deathaxe** [comment]
It appears Package Control ignores _Default_ and _User_ package. So there's not much we can do about update notification from our end.

**Comment by michaelblyons** [comment]
Okay. I thought that might be the case. 😞 Thanks for checking!

Seems like the easiest way to update is to delete `"Default",` from _Package Control.sublime-settings_ and ask PC to install "Default" again.
