### ISSUE TITLE
What is current status of ST4 support?

### ISSUE THREAD

**Issue by ratijas** [deathaxe/sublime-commands#7]
Now that ST~4~ is out, there's almost no reason to stick to ST3 anymore.

However, README still mentions ST3 config location (which is backward compatible, unless user creates separate ST~4~ directory).

Also, are new menus all there? Not that I know of any, but just for the sake of asking on topic.

**Comment by deathaxe** [comment]
This repo is kept up to date with the most recent builds available.

> Also, are new menus all there? 

This repo doesn't provide any menues. It just adds all their commands to command palette.

Yes, there are several new commands, but I don't maintain any changelogs or documentation.

The repo is mainly for personal use.
